backend:
  name: github
  repo: yutila-org/web
  branch: main

media_folder: public/assets/uploads
public_folder: /assets/uploads

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    extension: md
    fields:
      - { name: title, label: Title, widget: string }
      - { name: publishDate, label: Publish Date, widget: datetime }
      - { name: author, label: Author, widget: select, options: ["Acrilic", "Spider-Kyle"] }
      - name: category
        label: Category
        widget: select
        options:
          - Devlog
          - Publication
          - Report
          - Material
          - Resource
      - { name: body, label: Body, widget: markdown }
