name: "Stage 3: DAST"

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap-scan:
    name: zap-full-scan
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ vars.DAST_TARGET_URL }}
          rules_file_name: ""
          cmd_options: "-a"
